[package]
name = "mcworld"
version = "0.1.0"
authors = ["Daniël Louwrink <daniel.louwrink@gmail.com>"]
edition = "2018"

[dependencies]
leveldb = { path = "../leveldb" }
hematite-nbt = { path = "../hematite_nbt" }
byteorder = "1.2"
failure = "0.1"
fnv = "1.0"
